deptAbbr = {'Africana Studies':'AFR',
   	    'American Studies':'AMST',
   	    'Anthropology':'ANTH',
   	    'Arabic':'ARAB',
   	    'Architecture':'ARCH',
   	    'Art':'ART',
   	    'Art History':'ARTH',
   	    'Art Studio':'ARTS',
   	    'Astrophysics':'ASPH',
   	    'Astronomy':'ASTR',
   	    'Biological Chemistry':'BIOC',
            'Biological Sciences':'BISC',
   	    'Cinema and Media Studies':'CAMS',
	    'Chemistry':'CHEM',
	    'Chinese Language & Culture':'CHIN',
	    'Classical Civilization':'CLSC',
	    'Cognitive & Linguistic Sciences':'CSPW',
	    'Cognitive and Linguistic Sciences':'CSPW',
	    'Classics':'CLST',
	    'Comparative Literature':'CPLT',
	    'Computer Science':'CS',
	    'East Asian Studies':'EALC',
	    'Economics':'ECON',
	    'Education':'EDUC',
	    'English and Creative Writing':'ENG',
	    'English':'ENG',
	    'Environmental Studies':'ES',
	    'French':'FREN',
	    'French Cultural Studies':'FRST',
	    'Geosciences':'GEOS',
	    'German Studies':'GER',
	    'History':'HIST',
	    'International Relations':'IR',
	    'International Relations-Economics':'IREC',
	    'International Relations-History':'IRH',
	    'International Relations-Political Science':'IRPS',
	    'Italian Studies':'ITST',
	    'Japanese Language & Culture':'JPLC',
	    'Jewish Studies':'JWST',
	    'Latin American Studies':'LAST',
	    'Media Arts and Sciences':'MAS',
	    'Mathematics':'MATH',
	    'Medieval/Renaissance Studies':'MER',
	    'Middle Eastern Studies':'MES',
	    'Music':'MUS',
	    'Neuroscience':'NEUR',
	    'Peace and Justice Studies':'PEAC',
	    'Philosophy':'PHIL',
	    'Physics':'PHYS',
	    'Political Science':'POLS',
	    'Psychology':'PSYC',
	    'Russian Area Studies':'RAS',
	    'Religion':'REL',
	    'Russian':'RUSS',
	    'South Asian Studies':'SAS',
	    'Sociology':'SOC',
	    'Spanish':'SPAN',
	    'Theatre Studies':'THST',
	    'Undeclared':'UNDL',
	    "Women's & Gender Studies":'WGST',
	    'Writing':'WRIT'}

inv_deptAbbr = {v:k for k,v in deptAbbr.items()}

variantDeptAbbr = {'Africana Studies':'AFR',
   	    'American Studies':'AMST',
   	    'Anthropology':'ANTH',
   	    'Arabic':'ARAB',
   	    'Architecture':'ARCH',
   	    'Art':'ART',
   	    'Art History':'ARTH',
   	    'Art Studio':'ARTS',
   	    'Astrophysics':'ASPH',
   	    'Astronomy':'ASTR',
   	    'Biological Chemistry':'BIOC',
            'Biological Sciences':'BISC',
   	    'Cinema and Media Studies':'CAMS',
	    'Chemistry':'CHEM',
	    'Chinese':'CHIN',
	    'Chinese Studies':'CHIN',
	    'Chinese Language & Culture':'CHIN',
	    'Classical Civilization':'CLSC',
	    'Cognitive & Linguistic Sciences':'CSPW',
	    'Classics':'CLST',
	    'Comparative Literature':'CPLT',
	    'Computer Science':'CS',
	    'East Asian Studies':'EALC',
	    'Economics':'ECON',
	    'Education':'EDUC',
	    'English and Creative Writing':'ENG',
	    'English':'ENG',
	    'Environmental Studies':'ES',
	    'French':'FREN',
	    'French Cultural Studies':'FRST',
	    'Geosciences':'GEOS',
	    'German Studies':'GER',
	    'History':'HIST',
	    'International Relations-Economics':'IREC',
	    'International Relations-History':'IRH',
	    'International Relations-Political Science':'IRPS',
	    'Italian Studies':'ITST',
	    'Japanese Language & Culture':'JPLC',
	    'Jewish Studies':'JWST',
	    'Latin American Studies':'LAST',
	    'Media Arts':'MAS',
	    'Media Arts and Sciences':'MAS',
	    'Mathematics':'MATH',
	    'Medieval/Renaissance Studies':'MER',
	    'Middle Eastern Studies':'MES',
	    'Music':'MUS',
	    'Neuroscience':'NEUR',
	    'Peace':'PEAC',
	    'Philosophy':'PHIL',
	    'Physics':'PHYS',
	    'Political Science':'POLS',
	    'Psychology':'PSYC',
	    'Russian Area Studies':'RAS',
	    'Religion':'REL',
	    'Russian':'RUSS',
	    'South Asian Studies':'SAS',
	    'Sociology':'SOC',
	    'Spanish':'SPAN',
	    'Theatre Studies':'THST',
	    'Undeclared':'UNDL',
	    "Women's":'WGST',
	    "Women's and Gender Studies":'WGST',
	    "Women's & Gender Studies":'WGST',
	    'Writing':'WRIT'}